name: get proton config
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

permissions:
  contents: write

jobs:
  update-vpn-configs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install selenium requests

      - name: Run Downloader Script
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python proton_downloader_chrome.py
      
      - name: Run WG to Clash converter
        run: python wg2clash.py

      - name: Commit clash_proxies.yaml to repo
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

          # 只添加目标文件
          git add clash_proxies.yaml

          # 没变化就跳过提交
          git commit -m "🔄 Update clash_proxies.yaml [$(date)]" || echo "No changes to commit"

          git push
      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ProtonVPN_WireGuard_Configs
          name: "WireGuard Configs - Latest Update"
          files: |
            ProtonVPN_WireGuard_Configs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}